spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pathfinder?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    password: 12345
    username: root
#  servlet:
#    multipart:
#      max-file-size: 1MB
#      max-request-size: 5MB
#    mvc:
#      hiddenmethod:
#        filter:
#          enabled: true
#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED

logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.orm.jdbc.bind: TRACE
    sql: DEBUG

#cloudinary:
#  api-key:
#  api-secret:
#  cloud-name:

server:
  port: 8080
